"""Generates Centrica-branded Word documents — RFP, response templates, audit report."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import RGBColor, Pt, Cm

from rfx_assistant.branding import NAVY, MINT, LAVENDER, PALE_LAVENDER, PURPLE
from rfx_assistant.paths import OUTPUTS


def _rgb(hex_color: str) -> RGBColor:
    return RGBColor.from_string(hex_color.lstrip("#"))


def _set_cell_shading(cell, hex_color: str):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color.lstrip("#"))
    tc_pr.append(shd)


def _styled_doc() -> Document:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    sec = doc.sections[0]
    sec.left_margin = sec.right_margin = Cm(2.0)
    sec.top_margin = sec.bottom_margin = Cm(2.0)
    return doc


def _branded_heading(doc: Document, text: str, level: int = 1, color: str = NAVY):
    p = doc.add_heading(text, level=level)
    for run in p.runs:
        run.font.name = "Arial"
        run.font.color.rgb = _rgb(color)
    return p


def _cover_block(doc: Document, title: str, subtitle: str, meta: list[tuple[str, str]]):
    p = doc.add_paragraph()
    r = p.add_run("Centrica Procurement Transformation")
    r.bold = True
    r.font.color.rgb = _rgb(PURPLE)
    r.font.size = Pt(11)
    r.font.name = "Arial"

    p = doc.add_paragraph()
    r = p.add_run(title)
    r.bold = True
    r.font.color.rgb = _rgb(NAVY)
    r.font.size = Pt(26)
    r.font.name = "Arial"

    p = doc.add_paragraph()
    r = p.add_run(subtitle)
    r.italic = True
    r.font.color.rgb = _rgb("555555")
    r.font.size = Pt(12)

    doc.add_paragraph()
    tbl = doc.add_table(rows=len(meta), cols=2)
    tbl.style = "Light Grid Accent 1"
    for i, (k, v) in enumerate(meta):
        c1 = tbl.rows[i].cells[0]
        c2 = tbl.rows[i].cells[1]
        c1.text = k
        c2.text = v
        for run in c1.paragraphs[0].runs:
            run.font.bold = True
            run.font.color.rgb = _rgb(NAVY)
        _set_cell_shading(c1, PALE_LAVENDER)
    return tbl


# ----------------- RFP document -----------------

def render_rfp(category_strategy: str, library: dict, *, scoring_framework: dict) -> Path:
    """Produce a Centrica-formatted RFP Word document. Returns the saved path."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = OUTPUTS / f"RFP_DataCentreCooling_{ts}.docx"

    doc = _styled_doc()
    _cover_block(
        doc,
        "Request for Proposal",
        "Data Centre Cooling Systems — IT-INF-DC-COOL-2026",
        [
            ("Issued by",     "Centrica plc — Procurement, IT & Digital category"),
            ("Category lead", "Priya Rai, Senior Category Manager"),
            ("Sponsor",       "Mark Hendricks, Director of IT Infrastructure"),
            ("RFP reference", "IT-INF-DC-COOL-2026"),
            ("Issue date",    datetime.now().strftime("%d %B %Y")),
            ("Q&A close",     "5 June 2026, 17:00 BST"),
            ("Submission",    "19 June 2026, 17:00 BST via SAP Ariba Sourcing"),
            ("Award target",  "w/c 4 August 2026"),
        ],
    )
    doc.add_page_break()

    # 1. Introduction
    _branded_heading(doc, "1. Introduction", 1)
    doc.add_paragraph(
        "Centrica plc — operating across British Gas, Centrica Business Solutions, Bord Gáis Energy, "
        "Centrica Energy Storage, and Spirit Energy — is consolidating its IT estate as part of the "
        "FY26–FY28 Connected Home & Net Zero Infrastructure programme. This Request for Proposal seeks "
        "a small number of strategic suppliers to deliver Tier III+ data centre cooling across four new "
        "regional edge data centres (Slough, Manchester, Glasgow, Cardiff) and two refresh sites "
        "(Hams Hall, Reading West)."
    )
    doc.add_paragraph(
        "This RFP has been generated by the RFx Assistant from the approved Category Strategy "
        "(IT-INF-DC-COOL-2026, dated 12 February 2026) and the Centrica-curated Sourcing Library for "
        "Data Centre Cooling Systems. Suppliers must respond using the standardised templates issued "
        "alongside this document and lodge any boilerplate deviations in the supplied Deviation Register."
    )

    # 2. Demand signal
    _branded_heading(doc, "2. Demand signal", 1)
    rows = [
        ["Site", "IT load (MW)", "Cooling load (MW)", "Scope", "Go-live"],
        ["Slough East (new)",            "8.0", "9.6", "Full chilled water + CRAH", "Q4 2026"],
        ["Manchester Trafford (new)",    "6.5", "7.8", "Full chilled water + CRAH", "Q1 2027"],
        ["Glasgow Eurocentral (new)",    "5.0", "6.0", "Full chilled water + CRAH", "Q2 2027"],
        ["Cardiff Imperial Park (new)",  "5.0", "6.0", "Full chilled water + CRAH", "Q3 2027"],
        ["Hams Hall (refresh)",          "4.0", "4.8", "CRAH refresh + free cooling retrofit", "Q3 2026"],
        ["Reading West (refresh)",       "3.5", "4.2", "CRAH refresh + economiser retrofit", "Q4 2026"],
        ["TOTAL",                        "32.0","38.4","",  ""],
    ]
    tbl = doc.add_table(rows=len(rows), cols=5)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            c = tbl.rows[i].cells[j]
            c.text = val
            if i == 0:
                _set_cell_shading(c, NAVY)
                for run in c.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True
            elif i == len(rows) - 1:
                _set_cell_shading(c, MINT)
                for run in c.paragraphs[0].runs:
                    run.font.bold = True

    # 3. Sourcing approach
    _branded_heading(doc, "3. Sourcing approach", 1)
    doc.add_paragraph(
        "A two-stage RFP, published via SAP Ariba Sourcing. Stage 1 (RFI, completed) shortlisted five "
        "suppliers. This Stage 2 RFP closes the field to three suppliers for SME panel review, with single "
        "award per regional cluster (A, B, C). A supplier may bid for one, two, or all three clusters; "
        "Centrica will not award all three to a single supplier (single-source risk)."
    )
    cluster_rows = [
        ["Cluster", "Sites"],
        ["A", "Slough East + Hams Hall + Reading West (M4 corridor)"],
        ["B", "Manchester Trafford + Glasgow Eurocentral"],
        ["C", "Cardiff Imperial Park"],
    ]
    tbl = doc.add_table(rows=len(cluster_rows), cols=2)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(cluster_rows):
        for j, val in enumerate(row):
            c = tbl.rows[i].cells[j]
            c.text = val
            if i == 0:
                _set_cell_shading(c, NAVY)
                for run in c.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True

    # 4. Mandatory requirements
    doc.add_page_break()
    _branded_heading(doc, "4. Mandatory requirements", 1)
    for req in [
        "Tier III+ uptime certification of CRAH unit families bid (Uptime Institute or TIA-942 evidence).",
        "N+1 redundancy on every cooling subsystem — chilled water plant, CRAH, pumps, controls.",
        "PUE design point ≤ 1.25 at full IT load, ASHRAE A1 envelope, UK climate.",
        "Water-side economiser or equivalent free cooling active for ≥ 4,200 hours/year (UK Met Office TMY3).",
        "F-Gas Regulation (EU 517/2014, retained UK law) compliance — refrigerants with GWP ≤ 675 only at award; phase-down to GWP ≤ 150 by 31 December 2030.",
        "ISO 14001, ISO 45001, ISO 27001 at corporate and site level for all maintenance activities.",
        "Modern Slavery Act 2015 statement + tier-2 supply chain disclosure for chiller compressors, refrigerants, and rare-earth components.",
        "24/7/365 UK-based critical-response engineering, 4-hour response SLA, 8-hour fix SLA.",
    ]:
        doc.add_paragraph(req, style="List Bullet")

    # 5. Response sections — sourced from sourcing library
    doc.add_page_break()
    _branded_heading(doc, "5. Response sections", 1)
    doc.add_paragraph(
        "Suppliers must respond to every question in every section below. Standardised response templates "
        "are issued separately as Word and Excel attachments. The questions have been drawn from the "
        "Centrica-curated Sourcing Library for Data Centre Cooling Systems (last reviewed "
        f"{library.get('data_centre_cooling', {}).get('last_reviewed', '2026-02-12')})."
    )
    cooling_lib = library.get("data_centre_cooling", {})
    for sec in cooling_lib.get("sections", []):
        _branded_heading(doc, f"5.{sec['id']} — {sec['title']}", 2, color=PURPLE)
        for q in sec.get("questions", []):
            doc.add_paragraph(q, style="List Number")

    # 6. Boilerplate
    doc.add_page_break()
    _branded_heading(doc, "6. Boilerplate terms", 1)
    doc.add_paragraph(
        "Centrica's mandatory boilerplate is supplied as a separate document. Suppliers must accept verbatim "
        "or log a deviation in the Deviation Register. The most-frequently-deviated clauses are highlighted "
        "below and will form the focus of contract negotiation:"
    )
    for clause in [
        "Liability cap — 125% of charges paid in the prior 12 months (Centrica position).",
        "Service credits — 7.5% (response breach) and 12.5% (fix breach) of monthly Service Charges.",
        "Termination for convenience — 90 days' written notice, capped supplier recovery at 3% of remaining unperformed contract value.",
        "Step-in rights — 20 Business Days notice on Material Default; immediate on Insolvency Event.",
        "Sustainability covenants — make-up water ≤ 1.6 L/kWh of IT load; refrigerant GWP ≤ 150 by 31 December 2030.",
        "Insurance — Employer's £10m, Public £25m, Professional Indemnity £25m, Product £10m.",
    ]:
        doc.add_paragraph(clause, style="List Bullet")

    # 7. Evaluation framework
    doc.add_page_break()
    _branded_heading(doc, "7. Evaluation framework", 1)
    doc.add_paragraph(
        "Centrica will score bids using the framework below. Procurement scores commercial, social, "
        "implementation, resilience, and risk pillars. Technical and Sustainability pillars are scored by "
        "the SME panel; Procurement does NOT override SME scores on those pillars."
    )
    rows = [["Criterion", "Pillar", "Weight", "Scored by"]]
    for c in scoring_framework.get("criteria", []):
        rows.append([c["title"], c["pillar"], f"{c['weight']}%", c["scored_by"]])
    rows.append(["TOTAL", "", "100%", ""])
    tbl = doc.add_table(rows=len(rows), cols=4)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            cell = tbl.rows[i].cells[j]
            cell.text = val
            if i == 0:
                _set_cell_shading(cell, NAVY)
                for run in cell.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True
            elif i == len(rows) - 1:
                _set_cell_shading(cell, MINT)
                for run in cell.paragraphs[0].runs:
                    run.font.bold = True

    # 8. Timeline
    doc.add_page_break()
    _branded_heading(doc, "8. Timeline", 1)
    rows = [
        ["Milestone", "Target date"],
        ["RFP issue (this document)",          "w/c 11 May 2026"],
        ["Supplier Q&A window closes",         "5 June 2026"],
        ["Bid submission deadline",            "19 June 2026"],
        ["SME panel scoring",                  "w/c 6 July 2026"],
        ["Procurement Council recommendation", "28 July 2026"],
        ["Award & contract negotiation start", "w/c 4 August 2026"],
        ["First site mobilisation (Hams Hall)","1 October 2026"],
    ]
    tbl = doc.add_table(rows=len(rows), cols=2)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            cell = tbl.rows[i].cells[j]
            cell.text = val
            if i == 0:
                _set_cell_shading(cell, NAVY)
                for run in cell.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True

    # 9. Contacts
    _branded_heading(doc, "9. Contacts & process", 1)
    doc.add_paragraph(
        "All Q&A is via the SAP Ariba Sourcing event message board. Direct supplier-to-buyer contact "
        "outside the Ariba message board is not permitted during the live RFP and may result in disqualification."
    )
    doc.add_paragraph("Procurement contact: Priya Rai (Senior Category Manager) — accessed only via Ariba.")
    doc.add_paragraph("Technical SME chair: Neil Gallagher (Principal Critical-Facilities Engineer).")
    doc.add_paragraph("TPRM lead: Aisha Bello.")
    doc.add_paragraph("ESG sign-off: Rob Fenwick.")

    doc.add_paragraph()
    p = doc.add_paragraph()
    r = p.add_run("— End of RFP —")
    r.italic = True
    r.font.color.rgb = _rgb(PURPLE)

    doc.save(out)
    return out


# ----------------- Response template -----------------

def render_response_template(section_id: str, section_title: str, questions: Iterable[str]) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = OUTPUTS / f"ResponseTemplate_{section_id}_{ts}.docx"
    doc = _styled_doc()
    _cover_block(
        doc,
        f"Supplier Response Template — Section {section_id}",
        f"{section_title}",
        [
            ("RFP reference", "IT-INF-DC-COOL-2026"),
            ("Section",       f"{section_id} — {section_title}"),
            ("Format",        "Standardised Word template — answer in the boxes provided"),
            ("Issued by",     "Centrica Procurement, IT & Digital category"),
        ],
    )
    doc.add_page_break()
    _branded_heading(doc, f"Section {section_id} — {section_title}", 1)
    for i, q in enumerate(questions, start=1):
        _branded_heading(doc, f"Question {section_id}.{i}", 2, color=PURPLE)
        doc.add_paragraph(q)
        p = doc.add_paragraph()
        r = p.add_run("[Supplier response — max 800 words]")
        r.italic = True
        r.font.color.rgb = _rgb("888888")
        # answer placeholder box
        tbl = doc.add_table(rows=1, cols=1)
        tbl.style = "Light Grid Accent 1"
        tbl.rows[0].cells[0].text = " "
        tbl.rows[0].height = Cm(3)
    doc.save(out)
    return out


# ----------------- Audit report -----------------

def render_audit_report(state: dict) -> tuple[Path, Path]:
    """Emit the governance-ready Word + JSON pair."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    word_out = OUTPUTS / f"AuditReport_{ts}.docx"
    json_out = OUTPUTS / f"AuditReport_{ts}.json"

    # ---- JSON ----
    audit_json = {
        "event_id": f"RFX-{ts}",
        "ariba_event_id": "Doc12876211",
        "category": "IT-INF-DC-COOL-2026 — Data Centre Cooling Systems",
        "ranking": state.get("ranking", []),
        "decision": state.get("award_summary", {}),
        "deviations": state.get("contract_deviations_consolidated", []),
        "audit_metadata": {
            "generated_at": datetime.now().isoformat() + "Z",
            "tool": "RFx Assistant v0.1.0",
            "models_used": ["gemini-2.0-flash (primary)", "gemini-2.0-flash-lite (parsing)"],
            "human_in_loop": ["Priya Rai (Procurement)", "Neil Gallagher (SME)", "Rob Fenwick (ESG)", "Aisha Bello (TPRM)"],
            "framework_id": "SF-COOL-2026-v1",
        },
    }
    json_out.write_text(json.dumps(audit_json, indent=2), encoding="utf-8")

    # ---- Word ----
    doc = _styled_doc()
    _cover_block(
        doc,
        "Governance Audit Report",
        "RFP IT-INF-DC-COOL-2026 — Data Centre Cooling Systems",
        [
            ("Event ID",         f"RFX-{ts}"),
            ("Ariba event ID",   "Doc12876211"),
            ("Category",         "IT-INF-DC-COOL-2026"),
            ("Generated",        datetime.now().strftime("%d %B %Y, %H:%M")),
            ("Tool",             "RFx Assistant v0.1.0"),
            ("For decision by",  "Procurement Council, 28 July 2026"),
        ],
    )

    doc.add_page_break()
    _branded_heading(doc, "1. Decision summary", 1)
    aw = state.get("award_summary", {})
    rows = [["Cluster", "Recommended supplier"]]
    for k, v in aw.items():
        rows.append([k, v])
    tbl = doc.add_table(rows=len(rows), cols=2)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            cell = tbl.rows[i].cells[j]
            cell.text = val
            if i == 0:
                _set_cell_shading(cell, NAVY)
                for run in cell.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True

    _branded_heading(doc, "2. Ranked shortlist with rationale", 1)
    for entry in state.get("ranking", []):
        _branded_heading(doc, f"#{entry['rank']} — {entry['supplier_name']} ({entry['weighted_score_pct']:.1f}%)", 2, color=PURPLE)
        doc.add_paragraph(entry.get("recommendation", ""))
        for r in entry.get("rationale_top3", []):
            doc.add_paragraph(r, style="List Bullet")
        if entry.get("watch_flags"):
            doc.add_paragraph("Watch flags:")
            for w in entry["watch_flags"]:
                doc.add_paragraph(w, style="List Bullet")

    _branded_heading(doc, "3. Consolidated contract deviations", 1)
    rows = [["Supplier", "Clause", "Centrica position", "Supplier position", "Negotiation room"]]
    for d in state.get("contract_deviations_consolidated", []):
        rows.append([d["supplier"], d["clause"], d["centrica_position"], d["supplier_position"], d["negotiation_room"]])
    tbl = doc.add_table(rows=len(rows), cols=5)
    tbl.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            cell = tbl.rows[i].cells[j]
            cell.text = val
            if i == 0:
                _set_cell_shading(cell, NAVY)
                for run in cell.paragraphs[0].runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.bold = True

    _branded_heading(doc, "4. Audit metadata", 1)
    md = audit_json["audit_metadata"]
    for k, v in md.items():
        doc.add_paragraph(f"{k}: {v if not isinstance(v, list) else ', '.join(v)}", style="List Bullet")

    doc.save(word_out)
    return word_out, json_out
